#!/usr/bin/env ruby
# encoding: utf-8
# 这个脚本将 mark down 文件中插入图片的标记, 
# 替换成 github 上可以访问的图片链接.
# 这样在 github 上可以直接看到图片, 
# 实现在线阅读.
#
# Samples:
#   参数指定要转换的翻译版本
#   $ ruby makeonline zh

require 'rubygems'
#require 'rdiscount'
require 'fileutils'
include FileUtils

# TODO 是否有必要将结果图片复制到语言文件夹下?
def figures(lang,&block)
	begin
		Dir["figures/18333*.png"].each do |file|
			cp(file, file.sub(/18333fig0(\d)0?(\d+)\-tn/, '\1.\2'))
		end
		Dir["#{lang}/figures/*.png"].each do |file|
			cp(file,"figures")
		end
		Dir["#{lang}/figures-dia/*.dia"].each do |file|
			png_dest= file.sub(/.*fig0(\d)0?(\d+).dia/, 'figures/\1.\2.png')
			system("dia -e #{png_dest} #{file}")
		end
		block.call
	ensure
		Dir["figures/18333*.png"].each do |file|
			system("mkdir", "-p", "figures-bak")
			cp(file.gsub(/18333fig0(\d)0?(\d+)\-tn/, '\1.\2'), "figures-bak/")
			rm(file.gsub(/18333fig0(\d)0?(\d+)\-tn/, '\1.\2'))
		end
	end
end

def noop(lang,&block)
	begin
		block.call
	ensure
	end
end

if ARGV.length == 0
  puts "you need to specify at least one language. For example: makeonline zh"
  exit
end

ARGV.each do |lang|
  noop (lang) do
    puts "convert content for '#{lang}' language"

    figure_title = 'Figure'
    book_title = 'Pro Git - professional version control'
    authors = 'Scott Chacon'
    comments = 'licensed under the Creative Commons Attribution-Non Commercial-Share Alike 3.0 license'
    if lang == 'ko'
      figure_title = '그림'
    elsif lang == 'ja'
      figure_title = '図'
    elsif lang == 'ru'
      figure_title = 'Рисунок'
      book_title = 'Pro Git — профессиональный контроль версий'
      authors = 'Скот Чакон'
      comments = 'Лицензия: Creative Commons Attribution-Non Commercial-Share Alike 3.0 license'
    elsif lang == 'es'
      figure_title = 'Figura'
    elsif lang == 'it'
      figure_title = 'Figura'
      comments = 'distribuito sotto licenza Creative Commons Attribution-Non Commercial-Share Alike 3.0'
    elsif lang == 'zh'
      figure_title = '图'
    elsif lang == 'zh-tw'
      figure_title = '圖'
    elsif lang == 'pt-br'
      figure_title = 'Figura'
    elsif lang == 'pl'
      figure_title = 'Rysunek'
      book_title = 'Pro Git — profesjonalna kontrola wersji'
      comments = 'udostępnione na licencji Creative Commons Attribution-Non Commercial-Share Alike 3.0 license'	 
    end

    book_content = %(<html xmlns="http://www.w3.org/1999/xhtml"><head><title>#{book_title}</title></head><body>)
    dir = File.expand_path(File.join(File.dirname(__FILE__), lang))
    Dir[File.join(dir, '**', '*.markdown')].sort.each do |input|
      puts "processing #{input}"
      content = File.read(input)
      #content.gsub!(/Insert\s18333fig\d+\.png\s*\n.*?(\d{1,2})-(\d{1,2})\. (.*)/, '![\1.\2 \3](figures/\1.\2.png "\1.\2 \3")')
      content.gsub!(/Insert\s(18333fig\d+\.png)\s*\n(.*?)(\d{1,2})-(\d{1,2})\. (.*)/, '![\3.\4 \5](../../../../raw/master/figures/\1 "\3.\4 \5")\n\n\2\3-\4. \5')
      #book_content << RDiscount.new(content).to_html
      File.open(input, "w") do |output|
        output.write(content)
      end
    end
    book_content << "</body></html>"

  end
end
